name: 'Create Pull Request'
description: 'Creates Pull Request if git status --porcelain is not null'
author: 'uday31in'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  pr-message:
    description: 'Comment to post on an individuals first pull request'
runs:
  using: 'docker'
  image: 'Dockerfile'