name: CI

on: [push,repository_dispatch]

jobs:
  
  git:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1    
    - name: printenv
      run: printenv
    - name: pwd
      run: pwd      
    - name: print all enviornment variables in psh shell
      run: "Get-ChildItem env:"
      shell: pwsh
    - name: pwsh shell GITHUB_WORKSPACE
      run: "write-host GITHUB_WORKSPACE: $env:GITHUB_WORKSPACE"
      shell: pwsh
    - name: default shell GITHUB_WORKSPACE
      run: "echo GITHUB_WORKSPACE: $GITHUB_WORKSPACE"      
    - name: change directory      
      run: "cd $GITHUB_WORKSPACE; pwd;ls -alh;cd .. ; ls -alh"
    - name: tocuh file
      run: "touch $GITHUB_WORKSPACE/test.txt"
    - name: createpullrequest
      uses: ./actions/createpullrequest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   

      
  
