name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Run a one-line script
      run: echo Hello, world!
    - name: powershell
      shell: powershell 
      run: $PSVersionTable
    - name: print enviornment variable
      shell: powershell
      run: "Get-ChildItem env:"
    - name: get ps modules
      shell: pwsh 
      run: get-module -listavailable
      
  pwsh:
    runs-on: ubuntu-latest
    steps:    
    - name: install az
      shell: pwsh 
      run: Install-Module -Name Az
    - name: get ps modules
      shell: pwsh 
      run: get-module -listavailable
    
